title: Design Research
description: Вэб дизайны жишиг, стандарт, практик дүрмүүдийн нэгдсэн тэмдэглэл
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
